#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# CoSolvKit
#
# Turn annotated hotspots into runnable AutoPath refinement jobs.
#

import logging
import os
import subprocess

import numpy as np

from cosolvkit.analysis.sites.mmgbsa import (
    amber_exclude_mask,
    check_single_topology,
    write_frame_trajectory,
)
from cosolvkit.analysis.sites.poses import write_pose

logger = logging.getLogger(__name__)

SOLVENT_STRIP = ":HOH:WAT:Na+:Cl-"


def target_tag(target, is_binding_site):
    """Directory name for a refinement target.

    Hotspot ``site_id`` is unique only within a cosolvent, so a hotspot tag carries the
    probe name; binding-site ids are global.
    """
    if is_binding_site:
        return f"bs_{target.site_id}"
    return f"hs_{target.cosolvent}_{target.site_id}"


def select_mmgbsa_jobs(hotspot, args):
    """Pick (representative, selections) pairs for MMGBSA, best-occupied molecule first.

    A job is keyed by molecule because MMPBSA takes a single ligand mask: at a frame
    where a different copy occupied the blob, this molecule is elsewhere in the box.
    Records for the same molecule across replicas pool, since replicas share a topology
    — but frame indices are TRAJECTORY-LOCAL, so a pooled frame must stay attached to
    the record (and therefore the trajectory file) it came from. ``selections`` is
    ``[(ProbeOccupancy, [frame, ...]), ...]``, one entry per source record that
    contributed a chosen frame, ready to hand straight to :func:`write_frame_trajectory`.
    """
    records = list(hotspot.probe_occupancy)
    if args.mmgbsa_source is not None:
        records = [o for o in records if o.source_label == args.mmgbsa_source]
    if not records:
        return []

    by_molecule = {}
    for occ in records:
        by_molecule.setdefault((occ.probe_resname, occ.probe_resid), []).append(occ)

    ranked = sorted(
        by_molecule.items(),
        key=lambda kv: (-sum(o.n_frames_bound for o in kv[1]), kv[0][1]),
    )

    jobs = []
    for (_resname, _resid), occs in ranked[:args.mmgbsa_n_molecules]:
        check_single_topology(occs)
        representative = max(occs, key=lambda o: (o.n_frames_bound, o.source_label))

        # Frame indices are trajectory-local, so every candidate frame must stay
        # attached to the record it came from.
        candidates = [(i, f) for i, occ in enumerate(occs) for f in occ.frames]
        n = min(args.mmgbsa_n_frames, len(candidates))
        rng = np.random.default_rng(args.seed)
        picked = sorted(rng.choice(len(candidates), size=n, replace=False).tolist())

        by_record = {}
        for c in picked:
            i, f = candidates[c]
            by_record.setdefault(i, []).append(int(f))
        selections = [(occs[i], sorted(fs)) for i, fs in sorted(by_record.items())]
        jobs.append((representative, selections))
    return jobs


def render_autopath_script(manifest, mmgbsa, mode):
    """Render the per-target driver that calls AutoPath directly.

    ``AutoPath`` is imported from ``autopath.autopath_core``: it is not registered in
    ``autopath/__init__.py``'s lazy-import table, so ``from autopath import AutoPath``
    raises AttributeError.
    """
    lines = [
        "#!/usr/bin/env python",
        '"""Generated by refine_hotspots. Runs on a compute node, not a login node."""',
        "",
        "import MDAnalysis as mda",
        "",
        f"POSE_PDB = {manifest['pose_pdb']!r}",
        f"LIGAND_SELECTION = {manifest['ligand_selection']!r}",
        f"POCKET_SELECTION = {list(manifest['pocket_selection'])!r}",
        f"EXPECTED_POCKET_RESNAMES = {list(manifest['pocket_resnames'])!r}",
        "",
        "",
        "def check_pocket(pose_pdb):",
        '    """Verify POCKET_SELECTION still indexes the residues named in',
        "    EXPECTED_POCKET_RESNAMES in the pose file about to be handed to AutoPath.",
        '    Catches a stale or mismatched manifest before a simulation restrains the',
        '    wrong residues; it does not check AutoPath\'s post-preparation renumbering,',
        '    since the prepared system path is not known here."""',
        "    residues = mda.Universe(pose_pdb).residues",
        "    got = [residues[i - 1].resname for i in POCKET_SELECTION]",
        "    if got != EXPECTED_POCKET_RESNAMES:",
        "        raise SystemExit(",
        '            f"pocket_selection shifted during preparation: expected "',
        '            f"{EXPECTED_POCKET_RESNAMES}, got {got}"',
        "        )",
        "",
        "",
    ]

    if mode in ("smd", "both"):
        lines += [
            "from autopath.autopath_core import AutoPath",
            "",
            "check_pocket(POSE_PDB)",
            "",
            "ap = AutoPath(",
            "    pdb_path=POSE_PDB,",
            "    pocket_selection=POCKET_SELECTION,",
            "    run_preparation=True,",
            "    run_equilibration=True,",
            "    run_sMDpulling=True,",
            "    run_metadynamics=False,",
            ")",
            "ap.run(ligand_selection=LIGAND_SELECTION)",
            "",
        ]

    if mode in ("mmgbsa", "both") and mmgbsa is not None:
        lines += [
            "from autopath.ap_PLIP import ProteinLigandAnalyzer",
            "",
            "ProteinLigandAnalyzer.prepare_mmgbsa_batch(",
            f"    sysname={mmgbsa['sysname']!r},",
            f"    prmtop={mmgbsa['prmtop']!r},",
            f"    traj_fname={mmgbsa['trajectory']!r},",
            f"    ligand_amber_selection={mmgbsa['ligand_amber_selection']!r},",
            f"    strip_amber_selection={mmgbsa['strip_amber_selection']!r},",
            "    traj_slice=None,",
            f"    output_folder={mmgbsa['output_folder']!r},",
            "    radii='mbondi3',",
            ")",
            "",
        ]

    return "\n".join(lines)


def _slurm_script(tag, script_path, template_path=None):
    if template_path:
        with open(template_path) as fh:
            return fh.read().replace("{{SCRIPT}}", script_path).replace("{{NAME}}", tag)
    return "\n".join([
        "#!/bin/bash",
        f"#SBATCH --job-name={tag}",
        f"#SBATCH --output={tag}_%j.out",
        "#SBATCH --nodes=1",
        "#SBATCH --ntasks=1",
        "#SBATCH --cpus-per-task=8",
        "#SBATCH --time=24:00:00",
        "",
        f"python {script_path}",
        "",
    ])


def generate_jobs(config, results, out_dir, args):
    """Write pose, MMGBSA inputs and driver scripts for the top targets.

    :return: paths of the generated SLURM qfiles, in the order they were written.
    """
    targets = _rank_targets(config, results, args)
    qfiles = []

    for target, is_bs in targets:
        tag = target_tag(target, is_bs)
        tag_dir = os.path.join(out_dir, tag)
        os.makedirs(tag_dir, exist_ok=True)

        pose_ref = target.best_pose(gap_tolerance=args.gap_tolerance)
        if pose_ref is None:
            logger.warning(
                "Target %s has no occupancy record — no probe was ever inside it; "
                "skipping.", tag)
            continue

        manifest = write_pose(pose_ref, os.path.join(tag_dir, "pose.pdb"))

        mmgbsa_spec = None
        if args.mode in ("mmgbsa", "both"):
            mmgbsa_spec = _build_mmgbsa_inputs(target, tag, tag_dir, args)

        script_path = os.path.join(tag_dir, "run_autopath.py")
        with open(script_path, "w") as fh:
            fh.write(render_autopath_script(manifest, mmgbsa_spec, args.mode))

        qfile = os.path.join(tag_dir, "job.slurm")
        with open(qfile, "w") as fh:
            fh.write(_slurm_script(tag, script_path, args.slurm_template))
        qfiles.append(qfile)

    master = os.path.join(out_dir, "submit_all.sh")
    with open(master, "w") as fh:
        fh.write("#!/bin/bash\n")
        for q in qfiles:
            fh.write(f"sbatch {q}\n")
    os.chmod(master, 0o755)
    logger.info("Wrote %d job(s); master script %s.", len(qfiles), master)

    if args.submit:
        for q in qfiles:
            subprocess.run(["sbatch", q], check=True)
        logger.info("Submitted %d job(s).", len(qfiles))

    return qfiles


def _build_mmgbsa_inputs(target, tag, tag_dir, args):
    """Extract the frame trajectory and describe the prepare_mmgbsa_batch call."""
    jobs = select_mmgbsa_jobs(target, args)
    if not jobs:
        logger.warning("Target %s has no MMGBSA-eligible molecule; skipping that leg.",
                       tag)
        return None

    occ, selections = jobs[0]
    mm_dir = os.path.join(tag_dir, "mmgbsa")
    os.makedirs(mm_dir, exist_ok=True)
    write_frame_trajectory(selections, os.path.join(mm_dir, "frames.dcd"))

    import MDAnalysis as mda
    u = mda.Universe(occ.topology)
    all_resids = set(int(r) for r in
                     u.select_atoms(f"resname {occ.probe_resname}").resids)
    others = amber_exclude_mask(all_resids, keep=occ.probe_resid)

    return {
        "sysname": f"{tag}_{occ.probe_resname}{occ.probe_resid}_{occ.source_label}",
        "prmtop": occ.topology,
        "trajectory": os.path.join(mm_dir, "frames.dcd"),
        "ligand_amber_selection": occ.amber_mask,
        "strip_amber_selection": SOLVENT_STRIP + others,
        "output_folder": mm_dir,
    }


def _rank_targets(config, results, args):
    """Top-N refinement targets as ``[(target, is_binding_site), ...]``."""
    if args.target == "hotspots":
        flat = [h for sites in results.values() for h in sites]
        flat.sort(key=lambda h: (h.agfe_min if h.agfe_min is not None else 0.0))
        return [(h, False) for h in flat[:args.top_n]]

    from cosolvkit.analysis.sites.binding_sites import identify_binding_sites

    bs_cfg = config.binding_sites
    sites = identify_binding_sites(
        results,
        connectivity=bs_cfg.connectivity,
        weights=bs_cfg.weights,
        merge_tolerance_ang=bs_cfg.merge_tolerance_ang,
        probe_chemotype_overrides=bs_cfg.probe_chemotypes,
    )
    return [(s, True) for s in sites[:args.top_n]]
